#!/bin/bash
WALLPAPER_DIR="/home/vdt/Pictures/Wallpaper/"
#I dont know what the fuck I am doing
menu() {
  find "${WALLPAPER_DIR}" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) | awk '{print "img:"$0}'
}
main() {
  choice=$(menu | wofi -c ~/.config/wofi/wallpaper -s ~/.config/wofi/style-wallpaper.css --show dmenu --prompt "Select Wallpaper:" -n)
  selected_wallpaper=$(echo "$choice" | sed 's/^img://')
  swww img "$selected_wallpaper" --transition-type any --transition-fps 60 --transition-duration .3
  wal -i "$selected_wallpaper" -n --cols16

  # --- NEW PART STARTS HERE ---
  # Source the generated colors.sh to get the color variables
  source ~/.cache/wal/colors.sh

  # Construct the Hyprland colors file
  HYPR_COLORS_FILE="$HOME/.config/hypr/generated_colors.conf"
  TMP_HYPR_COLORS_FILE="$HYPR_COLORS_FILE.tmp"
  
  echo "# This file is automatically generated by wallpaper.sh. Do not edit manually." >"$TMP_HYPR_COLORS_FILE"
  echo "    \$wallpaper = $wallpaper" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$foregroundCol = 0xff${foreground:1}" >>"$TMP_HYPR_COLORS_FILE" # Remove '#' from hex code
  echo "    \$backgroundCol = 0xff${background:1}" >>"$TMP_HYPR_COLORS_FILE" # Remove '#' from hex code
  echo "    \$color0 = 0xff${color0:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color1 = 0xff${color1:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color2 = 0xff${color2:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color3 = 0xff${color3:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color4 = 0xff${color4:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color5 = 0xff${color5:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color6 = 0xff${color6:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color7 = 0xff${color7:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color8 = 0xff${color8:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color9 = 0xff${color9:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color10 = 0xff${color10:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color11 = 0xff${color11:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color12 = 0xff${color12:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color13 = 0xff${color13:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color14 = 0xff${color14:1}" >>"$TMP_HYPR_COLORS_FILE"
  echo "    \$color15 = 0xff${color15:1}" >>"$TMP_HYPR_COLORS_FILE"

  mv "$TMP_HYPR_COLORS_FILE" "$HYPR_COLORS_FILE"
  # --- NEW PART ENDS HERE ---

  swaync-client --reload-css
  cat ~/.cache/wal/colors-kitty.conf >~/.config/kitty/current-theme.conf
  kitty @ set-colors --all --configured ~/.config/kitty/current-theme.conf
  pywalfox update
  color1=$(awk 'match($0, /color2=\47(.*)\47/,a) { print a[1] }' ~/.cache/wal/colors.sh)
  color2=$(awk 'match($0, /color3=\47(.*)\47/,a) { print a[1] }' ~/.cache/wal/colors.sh)
  cava_config="$HOME/.config/cava/config"
  sed -i "s/^gradient_color_1 = .*/gradient_color_1 = '$color1'/" $cava_config
  sed -i "s/^gradient_color_2 = .*/gradient_color_2 = '$color2'/" $cava_config
  pkill -USR2 cava 2>/dev/null
  source ~/.cache/wal/colors.sh && cp -r $wallpaper ~/wallpapers/pywallpaper.jpg
  hyprctl reload
}
main
